AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False 
EPOCHS: 1
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.01

# hyperparameters search space for optuna

LEARNING_RATE_RANGE: [0.001, 0.01] #[0.00001, 0.001]
BATCH_SIZE_OPTIONS: [8] #[8, 16, 32]
EPOCHS_OPTIONS: [1] #[50, 100, 200, 500]
N_TRIALS: 1
TIMEOUT: 3600