artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1leEwKvCHlFMhQPlFUr8XQoSxp-79Qj_V/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


model_preparation:
  root_dir: artifacts/model_preparation
  base_model_path: artifacts/model_preparation/base_model.pth
  updated_base_model_path: artifacts/model_preparation/updated_base_model.pth


model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.pth
  training_data: artifacts/data_ingestion/Data/train
  validation_data: artifacts/data_ingestion/Data/valid
  test_data: artifacts/data_ingestion/Data/test
  updated_base_model_path: artifacts/model_preparation/updated_base_model.pth

model_evaluation:
  mlflow_tracking_uri: https://dagshub.com/riyosha/End-to-end-chest-cancer-classification.mlflow